-- Được require trong plugins/snacks.lua → init function (sau VeryLazy)
-- Hoặc dùng trực tiếp trong keys = { ... } của lazy spec nếu muốn lazy-load trigger

local M = {}

function M.setup()
  local km = require("utils.keymap")

  -- Top Pickers & Explorer
  km.n("<leader><space>", function()
    Snacks.picker.smart()
  end, "Smart Find Files")
  km.n("<leader>,", function()
    Snacks.picker.buffers()
  end, "Buffers")
  km.n("<leader>/", function()
    Snacks.picker.grep()
  end, "Grep")
  km.n("<leader>:", function()
    Snacks.picker.command_history()
  end, "Command History")
  km.n("<leader>n", function()
    Snacks.picker.notifications()
  end, "Notification History")
  km.n("<leader>e", function()
    Snacks.explorer()
  end, "File Explorer")

  -- find
  km.n("<leader>fb", function()
    Snacks.picker.buffers()
  end, "Buffers")
  km.n("<leader>fc", function()
    Snacks.picker.files { cwd = vim.fn.stdpath("config") }
  end, "Find Config File")
  km.n("<leader>ff", function()
    Snacks.picker.files()
  end, "Find Files")
  km.n("<leader>fg", function()
    Snacks.picker.git_files()
  end, "Find Git Files")
  km.n("<leader>fp", function()
    Snacks.picker.projects()
  end, "Projects")
  km.n("<leader>fr", function()
    Snacks.picker.recent()
  end, "Recent")

  -- git
  km.n("<leader>gb", function()
    Snacks.picker.git_branches()
  end, "Git Branches")
  km.n("<leader>gl", function()
    Snacks.picker.git_log()
  end, "Git Log")
  km.n("<leader>gL", function()
    Snacks.picker.git_log_line()
  end, "Git Log Line")
  km.n("<leader>gs", function()
    Snacks.picker.git_status()
  end, "Git Status")
  km.n("<leader>gS", function()
    Snacks.picker.git_stash()
  end, "Git Stash")
  km.n("<leader>gd", function()
    Snacks.picker.git_diff()
  end, "Git Diff (Hunks)")
  km.n("<leader>gf", function()
    Snacks.picker.git_log_file()
  end, "Git Log File")

  -- gh
  km.n("<leader>gi", function()
    Snacks.picker.gh_issue()
  end, "GitHub Issues (open)")
  km.n("<leader>gI", function()
    Snacks.picker.gh_issue { state = "all" }
  end, "GitHub Issues (all)")
  km.n("<leader>gp", function()
    Snacks.picker.gh_pr()
  end, "GitHub PRs (open)")
  km.n("<leader>gP", function()
    Snacks.picker.gh_pr { state = "all" }
  end, "GitHub PRs (all)")

  -- Grep
  km.n("<leader>sb", function()
    Snacks.picker.lines()
  end, "Buffer Lines")
  km.n("<leader>sB", function()
    Snacks.picker.grep_buffers()
  end, "Grep Open Buffers")
  km.n("<leader>sg", function()
    Snacks.picker.grep()
  end, "Grep")
  km.nv("<leader>sw", function()
    Snacks.picker.grep_word()
  end, "Word/Selection")

  -- search
  km.n('<leader>s"', function()
    Snacks.picker.registers()
  end, "Registers")
  km.n("<leader>s/", function()
    Snacks.picker.search_history()
  end, "Search History")
  km.n("<leader>sa", function()
    Snacks.picker.autocmds()
  end, "Autocmds")
  -- removed duplicate <leader>sb
  km.n("<leader>sc", function()
    Snacks.picker.command_history()
  end, "Command History")
  km.n("<leader>sC", function()
    Snacks.picker.commands()
  end, "Commands")
  km.n("<leader>sd", function()
    Snacks.picker.diagnostics()
  end, "Diagnostics")
  km.n("<leader>sD", function()
    Snacks.picker.diagnostics_buffer()
  end, "Buffer Diagnostics")
  km.n("<leader>sh", function()
    Snacks.picker.help()
  end, "Help Pages")
  km.n("<leader>sH", function()
    Snacks.picker.highlights()
  end, "Highlights")
  km.n("<leader>si", function()
    Snacks.picker.icons()
  end, "Icons")
  km.n("<leader>sj", function()
    Snacks.picker.jumps()
  end, "Jumps")
  km.n("<leader>sk", function()
    Snacks.picker.keymaps()
  end, "Keymaps")
  km.n("<leader>sl", function()
    Snacks.picker.loclist()
  end, "Location List")
  km.n("<leader>sm", function()
    Snacks.picker.marks()
  end, "Marks")
  km.n("<leader>sM", function()
    Snacks.picker.man()
  end, "Man Pages")
  km.n("<leader>sp", function()
    Snacks.picker.lazy()
  end, "Search Plugin Spec")
  km.n("<leader>sq", function()
    Snacks.picker.qflist()
  end, "Quickfix List")
  km.n("<leader>sR", function()
    Snacks.picker.resume()
  end, "Resume")
  km.n("<leader>su", function()
    Snacks.picker.undo()
  end, "Undo History")
  km.n("<leader>uC", function()
    Snacks.picker.colorschemes()
  end, "Colorschemes")

  -- LSP
  km.n("gd", function()
    Snacks.picker.lsp_definitions()
  end, "Goto Definition")
  km.n("gD", function()
    Snacks.picker.lsp_declarations()
  end, "Goto Declaration")
  km.n("gr", function()
    Snacks.picker.lsp_references()
  end, "References", { nowait = true })
  km.n("gI", function()
    Snacks.picker.lsp_implementations()
  end, "Goto Implementation")
  km.n("gy", function()
    Snacks.picker.lsp_type_definitions()
  end, "Type Definition")
  km.n("gai", function()
    Snacks.picker.lsp_incoming_calls()
  end, "Incoming Calls")
  km.n("gao", function()
    Snacks.picker.lsp_outgoing_calls()
  end, "Outgoing Calls")
  km.n("<leader>ss", function()
    Snacks.picker.lsp_symbols()
  end, "LSP Symbols")
  km.n("<leader>sS", function()
    Snacks.picker.lsp_workspace_symbols()
  end, "Workspace Symbols")

  -- Other
  km.n("<leader>z", function()
    Snacks.zen()
  end, "Zen Mode")
  km.n("<leader>Z", function()
    Snacks.zen.zoom()
  end, "Zoom")
  km.n("<leader>.", function()
    Snacks.scratch()
  end, "Scratch Buffer")
  km.n("<leader>S", function()
    Snacks.scratch.select()
  end, "Scratch Select")

  -- FIX: tránh đè <leader>n
  km.n("<leader>sn", function()
    Snacks.notifier.show_history()
  end, "Notification History")

  km.n("<leader>bd", function()
    Snacks.bufdelete()
  end, "Delete Buffer")
  km.n("<leader>cR", function()
    Snacks.rename.rename_file()
  end, "Rename File")
  km.nv("<leader>gB", function()
    Snacks.gitbrowse()
  end, "Git Browse")
  km.n("<leader>gg", function()
    Snacks.lazygit()
  end, "Lazygit")
  km.n("<leader>un", function()
    Snacks.notifier.hide()
  end, "Dismiss Notifications")

  -- Terminal
  km.n("<C-/>", function()
    Snacks.terminal()
  end, "Terminal")
  km.n("<C-/>", function()
    Snacks.terminal()
  end, "Terminal")
  km.n("<leader>tf", function()
    Snacks.terminal(nil, {
      cwd = vim.fn.expand("%:p:h"),
      win = {
        style = "float",
        border = "rounded",
        width = 0.9,
        height = 0.9,
      },
    })
  end, "Terminal (file dir)")

  -- Scope text objects (Visual + Operator-pending)
  km.map({ "n", "x", "o" }, "ii", function()
    Snacks.scope.textobject("i")
  end, "Inner Scope")
  km.map({ "n", "x", "o" }, "ai", function()
    Snacks.scope.textobject("a")
  end, "Outer Scope")

  -- Jump between scopes
  km.n("[i", function()
    Snacks.scope.jump("up")
  end, "Jump to scope start")
  km.n("]i", function()
    Snacks.scope.jump("down")
  end, "Jump to scope end")

  km.map({ "n", "t" }, "]]", function()
    Snacks.words.jump(vim.v.count1)
  end, "Next Reference")
  km.map({ "n", "t" }, "[[", function()
    Snacks.words.jump(-vim.v.count1)
  end, "Prev Reference")
end

return M
